services:
  - type: static
    name: web-municipal-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist

  - type: web
    name: web-municipal-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
